"""Initial migration

Revision ID: 0eb27e1ad3f4
Revises: 
Create Date: 2025-07-07 04:59:00.488533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb27e1ad3f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('favorite_verses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('verse_number', sa.Integer(), nullable=False),
    sa.Column('surah_number', sa.Integer(), nullable=False),
    sa.Column('surah_name', sa.String(), nullable=False),
    sa.Column('surah_name_arabic', sa.String(), nullable=True),
    sa.Column('verse_arabic', sa.Text(), nullable=False),
    sa.Column('verse_translation', sa.Text(), nullable=True),
    sa.Column('verse_transliteration', sa.Text(), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_verses_id'), 'favorite_verses', ['id'], unique=False)
    op.create_table('prayer_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prayer_name', sa.String(), nullable=False),
    sa.Column('prayer_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prayed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prayer_logs_id'), 'prayer_logs', ['id'], unique=False)
    op.create_table('zakat_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_assets', sa.Float(), nullable=False),
    sa.Column('total_debts', sa.Float(), nullable=True),
    sa.Column('net_assets', sa.Float(), nullable=False),
    sa.Column('zakat_amount', sa.Float(), nullable=False),
    sa.Column('calculation_type', sa.String(), nullable=True),
    sa.Column('asset_breakdown', sa.JSON(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zakat_calculations_id'), 'zakat_calculations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zakat_calculations_id'), table_name='zakat_calculations')
    op.drop_table('zakat_calculations')
    op.drop_index(op.f('ix_prayer_logs_id'), table_name='prayer_logs')
    op.drop_table('prayer_logs')
    op.drop_index(op.f('ix_favorite_verses_id'), table_name='favorite_verses')
    op.drop_table('favorite_verses')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
