"""Add bookmarks table

Revision ID: 3dabf41564a6
Revises: 0eb27e1ad3f4
Create Date: 2025-07-07 05:19:41.120114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dabf41564a6'
down_revision: Union[str, None] = '0eb27e1ad3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
