// Centralized react-icons imports for tree-shaking
// This file exports only the icons we actually use, reducing bundle size

export {
  // Fi icons (Feather icons)
  FiArrowRight,
  FiAlertCircle,
  FiBell,
  FiBook,
  FiBookOpen,
  FiBookmark,
  FiCalendar,
  FiCheck,
  FiCheckCircle,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiClock,
  FiCloudSnow,
  FiCompass,
  FiCopy,
  FiDollarSign,
  FiDownload,
  FiExternalLink,
  FiFilter,
  FiGlobe,
  FiGrid,
  FiHeart,
  FiHelpCircle,
  FiInfo,
  FiList,
  FiLoader,
  FiLock,
  FiLogOut,
  FiMail,
  FiMapPin,
  FiMenu,
  FiMessageCircle,
  FiMoon,
  FiPause,
  FiPlay,
  FiRefreshCw,
  FiRepeat,
  FiSearch,
  FiSend,
  FiSettings,
  FiShare2,
  FiSkipBack,
  FiSkipForward,
  FiStar,
  FiSun,
  FiSunrise,
  FiSunset,
  FiTag,
  FiTrash2,
  FiUser,
  FiUsers,
  FiVolume2,
  FiVolumeX,
  FiX,
  FiXCircle,
} from 'react-icons/fi'